FROM python:3.10.7-slim

LABEL org.opencontainers.image.authors="https://github.com/nayotta" \
      org.opencontainers.image.ref.name="3.10.7-slim" \
      org.opencontainers.image.source="https://github.com/nayotta/opmachine-hextech"
      org.opencontainers.image.title="python" \
      org.opencontainers.image.version="3.10.7"

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y procps net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
