name: build test

on:
  release:
    types:
      - created

jobs:
  compile-amd64-and-upload-asset:
    strategy:
      matrix:
        distro:
          - ubuntu-20.04

    runs-on: ${{ matrix.distro }}

    steps:
      - name: Pull The Repository
        uses: actions/checkout@v3
        with:
          path: openmachine-hextech

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
        with:
          tagRegex: "v(.*)"

      - name: Prepare
        env:
          FREE_DISK_SCRIPT: https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh
        run: |
          mkdir -p dist
          curl ${FREE_DISK_SCRIPT} | bash

      - name: Build Arm
        uses: pguyot/arm-runner-action@v2
        env:
          PYTHON_VERSION: 3.10.7
        with:
          image_additional_mb: 1024
          base_image: raspios_lite:latest
          cpu: cortex-a7
          copy_artifact_path: opt/build-info.txt, opt/${PYTHON_VERSION}
          copy_artifact_dest: dist/build-info.txt, dist/${PYTHON_VERSION}
          commands: |
            apt-get update
            apt-get install git curl \
              build-essential zlib1g-dev libffi-dev libssl-dev \
              libbz2-dev libreadline-dev libsqlite3-dev liblzma-dev \
              libxml2-dev libxmlsec1-dev libxslt-dev -y
            curl https://pyenv.run | bash
            export PYENV_ROOT="$HOME/.pyenv"
            command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"

            pyenv install -v ${PYTHON_VERSION}

            mkdir -p opt
            mv ${PYENV_ROOT}/versions/${PYTHON_VERSION} opt/${PYTHON_VERSION}
            pyenv versions |tee >> opt/build-info.txt

      - name: Check Artifact
        env:
          PROJECT_PACKAGE: openmachine-hextech
          RUN_OS: linux
          RUN_ARCH: armhf
        run: |
          TAR_NAME="${PROJECT_PACKAGE}_${GIT_TAG_NAME}_${RUN_OS}_${RUN_ARCH}.tar.gz"
          cat dist/build-info.txt
          (cd dist; tar zcvf ../${TAR_NAME} build-info.txt)
          sha1sum ${TAR_NAME} > ${TAR_NAME}.sha1
          ls -l

      - name: Upload Artifact Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz
            *.sha1