name: build arm pyenv with python

on:
  release:
    types:
      - created
  push:
    tags:
      - pyenv-*

jobs:
  compile-arm-and-upload-asset:
    strategy:
      matrix:
        distro:
          - ubuntu-20.04
        include:
          - arm_cpu: cortex-a7
            arm_base_images: raspios_lite:latest
            python_version: 3.10.7

    runs-on: ${{ matrix.distro }}

    steps:
      - name: Pull The Repository
        uses: actions/checkout@v3
        with:
          path: openmachine-hextech

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
        with:
          tagRegex: "v(.*)"

      # - name: Free Disk
      #   env:
      #     FREE_DISK_SCRIPT: https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh
      #   run: |
      #     curl ${FREE_DISK_SCRIPT} | bash

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install tree -y
          mkdir -p dist
          pwd
          tree -L 2 .

      - name: Build Arm
        uses: pguyot/arm-runner-action@v2
        env:
          PROJECT_NAME: opmachine-hextech/pyenv
          PYTHON_VERSION: ${{ matrix.python_version}}
        with:
          image_additional_mb: 1024
          base_image: ${{ matrix.arm_base_images}}
          cpu: ${{ matrix.arm_cpu}}
          copy_artifact_path: opt
          copy_artifact_dest: dist/opt
          commands: |
            ${PROJECT_NAME}/prepare.sh
            ${PROJECT_NAME}/setup-pyenv.sh
            ${PROJECT_NAME}/install-python.sh
            ${PROJECT_NAME}/done.sh

      - name: Check Artifact
        env:
          PROJECT_PACKAGE: openmachine-hextech
          RUN_OS: linux
          RUN_ARCH: armhf
        run: |
          pwd
          tree -L 2 .
          TAR_NAME="${PROJECT_PACKAGE}_${GIT_TAG_NAME}_${RUN_OS}_${RUN_ARCH}.tar.gz"
          (cd dist; tar zcvf ../${TAR_NAME} opt)
          sha1sum ${TAR_NAME} > ${TAR_NAME}.sha1
          tree -L 2 .

      - name: Upload Artifact Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz
            *.sha1