name: build arm pyenv with python

on:
  push:
    tags:
      - pyenv-*

jobs:
  compile-arm-and-upload-asset:
    strategy:
      matrix:
        include:
          - distro: ubuntu-20.04
            arm_vm_runner:
              arch: armv7l
              cpu: cortex-a7
              image_additional_mb: 1024
              base_images: https://downloads.raspberrypi.org/raspios_oldstable_lite_armhf/images/raspios_oldstable_lite_armhf-2022-09-26/2022-09-22-raspios-buster-armhf-lite.img.xz
              distro: debian
              distro_codename: buster
            python_version: 3.10.7
            repo_project_name: opmachine-hextech

          - distro: ubuntu-20.04
            arm_vm_runner:
              arch: armv7l
              cpu: cortex-a7
              image_additional_mb: 1024
              base_images: raspios_lite:latest
              distro: debian
              distro_codename: bullseye
            python_version: 3.10.7
            repo_project_name: opmachine-hextech

          - distro: ubuntu-20.04
            arm_vm_runner:
              arch: aarch64
              cpu: cortex-a53
              image_additional_mb: 1024
              base_images: raspios_lite_arm64:latest
              distro: debian
              distro_codename: bullseye
            python_version: 3.10.7
            repo_project_name: opmachine-hextech

    runs-on: ${{ matrix.distro }}

    steps:
      - name: Pull The Repository
        uses: actions/checkout@v3
        with:
          path: ${{ matrix.repo_project_name }}

      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName
        with:
          tagRegex: "(.*)"

      # - name: Free Disk
      #   env:
      #     FREE_DISK_SCRIPT: https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh
      #   run: |
      #     curl ${FREE_DISK_SCRIPT} | bash

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install tree -y
          mkdir -p dist
          pwd
          tree -L 2 .

      - name: Build Arm
        uses: pguyot/arm-runner-action@v2
        env:
          # HOME: /home/pi
          # LOCAL_ENV: .bashrc
          PROJECT_NAME: ${{ matrix.repo_project_name }}/pyenv
          PYTHON_VERSION: ${{ matrix.python_version}}
        with:
          image_additional_mb: ${{ matrix.arm_vm_runner.image_additional_mb }}
          base_image: ${{ matrix.arm_vm_runner.base_images }}
          cpu: ${{ matrix.arm_vm_runner.cpu}}
          shell: /bin/bash -eo pipefail
          copy_artifact_path: opt/pyenv
          copy_artifact_dest: dist/pyenv
          # commands: |
          #   # ${PROJECT_NAME}/prepare.sh

          #   # ${PROJECT_NAME}/setup-pyenv.sh

          #   # ${PROJECT_NAME}/install-python.sh

          #   # ${PROJECT_NAME}/done.sh

          #   ls -la /home
          #   echo ${HOME}
          #   export LOCAL_ENV=${HOME}/${LOCAL_ENV}
          #   echo ${LOCAL_ENV}
          #   touch ${LOCAL_ENV}
          #   ls -la

          #   echo "1:start"
          #   ${PROJECT_NAME}/prepare.sh
          #   echo "1:done" ${ARTIFACT_OPT}
          #   . ${LOCAL_ENV}
          #   echo "1:end1" ${PATH}
          #   echo "1:end2" ${ARTIFACT_OPT}

          #   echo "2:start"
          #   cat ${PROJECT_NAME}/setup-pyenv.sh
          #   ${PROJECT_NAME}/setup-pyenv.sh
          #   ls -la
          #   cat ${LOCAL_ENV}
          #   ${PROJECT_NAME}/done.sh
          #   . ${LOCAL_ENV}
          #   echo "2:done1" $PATH
          #   echo "2:done2" ${ARTIFACT_OPT}
          #   pyenv --help
          #   echo "2: end"

          #   ${PROJECT_NAME}/install-python.sh
          #   echo "3:" ${ARTIFACT_OPT}
          #   ${PROJECT_NAME}/done.sh
          commands: |
            # prepare
            mkdir -p ${PWD}/opt
            export ARTIFACT_OPT="${PWD}/opt"
            cat /etc/issue
            cat /etc/os-release
            uname -a

            # install dependencies
            apt-get update
            apt-get install git curl tree \
              build-essential zlib1g-dev libffi-dev libssl-dev \
              libbz2-dev libreadline-dev libsqlite3-dev liblzma-dev \
              libxml2-dev libxmlsec1-dev libxslt-dev -y

            # install pyenv
            curl https://pyenv.run | bash

            # set env
            export PYENV_ROOT="$HOME/.pyenv"
            command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"

            # debug
            tree -L 2 .
            echo ${PYTHON_VERSION}
            echo ${PYENV_ROOT}
            echo ${ARTIFACT_OPT}
            echo $PATH
            pyenv versions

            # install python
            pyenv install -v ${PYTHON_VERSION}
            pyenv versions

            # copy pyenv
            mv ${PYENV_ROOT} ${ARTIFACT_OPT}/pyenv


      - name: Check Artifact
        env:
          PROJECT_PACKAGE: ${{ matrix.repo_project_name }}
          RUN_PKG_NAME: pyenv
          RUN_PYTHON_VERSION: cp-${{ matrix.python_version }}
          RUN_OS: ${{ matrix.arm_vm_runner.distro_codename }}
          RUN_ARCH: ${{ matrix.arm_vm_runner.arch }}
        run: |
          pwd
          tree -L 2 .
          TAR_NAME="${PROJECT_PACKAGE}_${RUN_PKG_NAME}_${RUN_PYTHON_VERSION}_${RUN_OS}_${RUN_ARCH}.tar.gz"
          (cd dist; tar zcvf ../${TAR_NAME} pyenv)
          sha1sum ${TAR_NAME} > ${TAR_NAME}.sha1
          tree -L 2 .

      - name: Upload Artifact Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz
            *.sha1